import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import {pbkdf2Sync} from 'node:crypto';
test('senha, sessão, CSRF, expiração, logout e limite de tentativas',async t=>{
 const req=createRequire(import.meta.url),wr=createRequire(req.resolve('wrangler/package.json'));
 const {Miniflare,convertV4MiniflareOptions}=wr('miniflare');
 const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:readFileSync('src/worker.mjs','utf8'),compatibilityDate:'2026-09-11',cf:false,bindings:{ADMIN_PASSWORD_SALT:'test-salt',ADMIN_PASSWORD_HASH:pbkdf2Sync('test-password','test-salt',100000,32,'sha256').toString('hex')},d1Databases:['DB']}));
 t.after(()=>mf.dispose());await mf.ready;const db=await mf.getD1Database('DB');for(const sql of readFileSync('migrations/0002_admin_password.sql','utf8').split(';').filter(s=>s.trim()))await db.prepare(sql).run();
 const call=(path,method='GET',body,cookie='',origin='https://site.example')=>mf.dispatchFetch('https://site.example'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});
 assert.equal((await call('/api/admin/context')).status,401);
 assert.equal((await call('/api/auth/login','POST',{password:'test-password'},'','https://evil.example')).status,403);
 assert.equal((await call('/api/auth/login','POST',{password:'wrong'})).status,401);
 const login=await call('/api/auth/login','POST',{password:'test-password'});assert.equal(login.status,200);const header=login.headers.get('Set-Cookie');assert.match(header,/HttpOnly/);assert.match(header,/Secure/);const cookie=header.split(';')[0];
 assert.equal((await call('/api/admin/context','GET',undefined,cookie)).status,200);
 assert.equal((await call('/api/admin/context','GET',undefined,'bufalo_admin='+'0'.repeat(64))).status,401);
 await call('/api/auth/logout','POST',{},cookie);assert.equal((await call('/api/admin/context','GET',undefined,cookie)).status,401);
 const login2=await call('/api/auth/login','POST',{password:'test-password'});const c2=login2.headers.get('Set-Cookie').split(';')[0];await db.prepare('UPDATE admin_sessions SET expires_at=0').run();assert.equal((await call('/api/admin/context','GET',undefined,c2)).status,401);
 for(let i=0;i<7;i++)await call('/api/auth/login','POST',{password:'wrong'});assert.equal((await call('/api/auth/login','POST',{password:'test-password'})).status,429);
});
