-- Artigos iniciais: histórias reais já publicadas na Loja Integrada.
INSERT OR IGNORE INTO blog_posts(slug,title,category,excerpt,image,image_alt,post_date,body,status,source_url,updated_at) VALUES
  ('bufalo-eco-hackathon-enactus-ufpa','Búfalo no Eco Hackathon: empreender para transformar','Enactus UFPA','Em fevereiro de 2026, a Búfalo participou da avaliação de projetos do 2º Eco Hackathon da Enactus UFPA e compartilhou sua experiência com negócios de impacto.','https://cdn.awsli.com.br/1237/1237589/arquivos/alex_ecohack.jpeg','Participação da Búfalo no Eco Hackathon da Enactus UFPA','2026-09-20','Em 21 de fevereiro de 2026, a Búfalo participou do 2º Eco Hackathon promovido pela Enactus UFPA. Alex Sandro foi convidado para integrar a avaliação dos projetos e ajudar a escolher a iniciativa que representaria a equipe nas competições daquele ano.

O encontro também abriu espaço para compartilhar uma trajetória empreendedora construída em campo. Antes da Búfalo, Alex trabalhou com desenvolvimento regional sustentável em Paragominas e com microcrédito produtivo orientado em Ananindeua. Foram experiências que aproximaram o trabalho com pequenos negócios das necessidades das comunidades locais.

Na conversa com os estudantes, ele apresentou a iniciativa Amazônia Potável e seu modelo de filtros portáteis. À época do encontro, segundo o relato publicado pela Búfalo, a iniciativa já havia beneficiado 189 famílias da Vila do Cuia, no Baixo Amazonas.

Os projetos avaliados no hackathon reuniam inovação, viabilidade econômica e impacto socioambiental. Para a Búfalo, participar desse processo foi uma oportunidade de trocar aprendizados com uma nova geração de empreendedores da Amazônia.','published','https://loja.bufalogrowler.com.br/pagina/empreender-e-gerar-impacto-nossa-participacao-no-eco-hackathon-da-enactus-ufpa.html','2026-09-20T00:00:00Z'),
  ('bufalo-enactus-ufpa-parceria-impacto','Búfalo e Enactus UFPA: uma parceria por impacto social','Parcerias','A marca apoiou a equipe da UFPA em sua jornada na Enactus World Cup 2025, conectando inovação, sustentabilidade e compromisso com comunidades amazônicas.','https://cdn.awsli.com.br/1237/1237589/arquivos/alex_enactus1.jpg','Representantes da Búfalo e da Enactus UFPA','2026-09-19','A parceria entre a Búfalo Growler e a Enactus UFPA nasceu de uma visão compartilhada: ideias empreendedoras podem responder a desafios reais das comunidades. A equipe da universidade foi escolhida para representar o Brasil na Enactus World Cup 2025.

Os projetos da Enactus UFPA combinam pesquisa, gestão e atuação social. O objetivo é transformar desafios locais em soluções que possam melhorar a vida de pessoas na Amazônia e inspirar outras iniciativas.

Ao apoiar a equipe, a Búfalo passou a fazer parte de uma rede de estudantes e parceiros que trabalham com inovação sustentável. A parceria foi apresentada pela marca como um apoio à formação de jovens empreendedores sociais e à circulação de ideias criadas no Pará.

A história mostra como uma colaboração pode ampliar o alcance de projetos locais sem perder de vista as pessoas e os territórios que deram origem a eles.','published','https://loja.bufalogrowler.com.br/pagina/bufalo-growler-e-enactus-ufpa-juntos-pelo-impacto-e-pela-inovacao.html','2026-09-20T00:00:00Z'),
  ('amazonia-potavel-negocio-social-na-pratica','Amazônia Potável: um negócio social na prática','Amazônia Potável','O projeto da Búfalo usa um modelo em que a venda de um filtro portátil viabiliza a doação de outro para comunidades ribeirinhas.','https://cdn.awsli.com.br/1237/1237589/arquivos/rib_amazonia.jpg','Comunidade ribeirinha da Amazônia retratada no artigo original','2026-09-18','A iniciativa Amazônia Potável surgiu de uma pergunta prática: como ampliar o acesso à água potável em comunidades ribeirinhas e, ao mesmo tempo, sustentar a continuidade do projeto?

O modelo apresentado pela Búfalo é direto. A cada filtro portátil vendido, outro é destinado a uma comunidade que precisa de uma solução para tratar água. Dessa forma, a compra também ajuda a financiar uma entrega social.

No artigo original, o cofundador Alex Sandro explica que impacto duradouro depende de organização, viabilidade econômica e parcerias. A proposta é integrar o compromisso social ao funcionamento do negócio, sem depender exclusivamente de doações eventuais.

A experiência também traz um convite para outros empreendedores: começar com uma ação concreta, acompanhar seus resultados e construir relações com organizações e comunidades locais. O objetivo é que propósito e operação caminhem juntos.','published','https://loja.bufalogrowler.com.br/pagina/negocio-social-como-empreendedores-podem-gerar-impacto-real-por-meio-de-seus-negocios.html','2026-09-20T00:00:00Z'),
  ('filtros-agua-comunidade-tikuna-solimoes','40 filtros de água chegam à comunidade Tikuná no Solimões','Comunidades','Em parceria com a iniciativa Amazônia Potável, Max Dacampo distribuiu filtros doados pela Búfalo a uma comunidade indígena às margens do rio Solimões.','https://cdn.awsli.com.br/1237/1237589/arquivos/max_rib_1.jpg','Ação de entrega de filtros de água na região do rio Solimões','2026-09-17','Uma ação realizada em 26 de abril levou 40 filtros de água a uma comunidade indígena Tikuná às margens do rio Solimões. Os filtros foram doados pela Búfalo Growler e distribuídos por Max Dacampo, parceiro da iniciativa Amazônia Potável.

A entrega fez parte de uma mobilização para ampliar o acesso a soluções de tratamento de água em comunidades da Amazônia. Em áreas isoladas, transportar água tratada ou instalar sistemas convencionais pode ser difícil; por isso, soluções portáteis têm um papel importante nessas ações.

Os filtros Hidrapuri descritos no relato original usam membrana de fibra oca e carvão ativado. A Búfalo apresenta essa tecnologia como uma alternativa portátil que dispensa energia elétrica para o uso.

A parceria com Max Dacampo mostra como uma rede de pessoas e projetos pode levar uma iniciativa além da ideia inicial. Cada entrega também ajuda a tornar mais visível o desafio do acesso à água segura na região.','published','https://loja.bufalogrowler.com.br/pagina/o-missionario-max-dacampo-leva-agua-potavel-a-comunidade-indigena-ticuna.html','2026-09-20T00:00:00Z');
