const local=['localhost','127.0.0.1'].includes(location.hostname);
const loginPanel=document.getElementById('login-panel'),editorPanel=document.getElementById('editor-panel'),form=document.getElementById('post-form');
const loginStatus=document.getElementById('login-status'),saveStatus=document.getElementById('save-status'),list=document.getElementById('admin-posts');
let posts=[];
const slugify=text=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90);
async function request(path,method='GET',data){const response=await fetch(`/blog/api/${path}`,{method,credentials:'same-origin',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const json=await response.json();if(!response.ok)throw Error(json.error||'Não foi possível concluir.');return json;}
async function demoLogin(password){const config=await fetch('/blog/preview-config.json').then(r=>r.json());const bytes=new TextEncoder().encode(config.salt+password);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');return hash===config.hash;}
async function load(){if(local){const seed=await fetch('/blog/posts.json').then(r=>r.json());const edited=JSON.parse(localStorage.getItem('bufalo_blog_preview_v2')||'{}');posts=[...seed.filter(p=>!(p.slug in edited)),...Object.values(edited)].filter(p=>!p.deleted).map(p=>({...p,status:p.status||'published'}));}else posts=(await request('admin/posts')).posts;render();}
function render(){list.replaceChildren();posts.sort((a,b)=>b.date.localeCompare(a.date));for(const post of posts){const li=document.createElement('li'),strong=document.createElement('strong'),small=document.createElement('small'),edit=document.createElement('button'),remove=document.createElement('button');strong.textContent=post.title;small.textContent=`${post.status==='published'?'Publicado':'Rascunho'} · ${post.date}`;edit.type='button';edit.textContent='Editar';edit.onclick=()=>editPost(post);remove.type='button';remove.textContent='Excluir';remove.onclick=()=>deletePost(post);li.append(strong,small,edit,remove);list.append(li)}if(!posts.length)list.textContent='Nenhum post cadastrado.';}
function editPost(post){for(const key of ['id','title','category','date','excerpt','image','imageAlt','body','sourceUrl','status'])form.elements[key].value=post[key]??(key==='id'?post.slug:'');document.getElementById('editor-title').textContent='Editar post';saveStatus.textContent='';form.scrollIntoView({behavior:'smooth'});}
function resetForm(){form.reset();form.elements.id.value='';form.elements.date.value=new Date().toISOString().slice(0,10);document.getElementById('editor-title').textContent='Novo post';saveStatus.textContent='';}
async function deletePost(post){if(!confirm(`Excluir “${post.title}”?`))return;try{if(local){const edited=JSON.parse(localStorage.getItem('bufalo_blog_preview_v2')||'{}');edited[post.slug]={...post,status:'draft',deleted:true};localStorage.setItem('bufalo_blog_preview_v2',JSON.stringify(edited));}else await request(`admin/posts/${encodeURIComponent(post.slug)}`,'DELETE');await load();resetForm();saveStatus.textContent='Post excluído.';}catch(e){saveStatus.textContent=e.message;}}
document.getElementById('login-form').onsubmit=async e=>{e.preventDefault();loginStatus.textContent='Verificando...';try{const password=document.getElementById('password').value;if(local){if(!await demoLogin(password))throw Error('Senha incorreta.');sessionStorage.setItem('bufalo_blog_preview_v2_auth_v2','1');}else await request('login','POST',{password});document.getElementById('password').value='';loginPanel.classList.add('hidden');editorPanel.classList.remove('hidden');if(local)document.getElementById('preview-note').classList.remove('hidden');await load();resetForm();}catch(err){loginStatus.textContent=err.message;}};
form.onsubmit=async e=>{e.preventDefault();saveStatus.textContent='Salvando...';const data=Object.fromEntries(new FormData(form));data.slug=data.id||slugify(data.title);delete data.id;if(!data.slug){saveStatus.textContent='Informe um título válido.';return;}try{if(local){const edited=JSON.parse(localStorage.getItem('bufalo_blog_preview_v2')||'{}');edited[data.slug]=data;localStorage.setItem('bufalo_blog_preview_v2',JSON.stringify(edited));}else await request('admin/posts','POST',data);await load();saveStatus.textContent=data.status==='published'?'Post publicado.':'Rascunho salvo.';form.elements.id.value=data.slug;}catch(err){saveStatus.textContent=err.message;}};
document.getElementById('new-post').onclick=resetForm;
document.getElementById('logout').onclick=async()=>{if(local)sessionStorage.removeItem('bufalo_blog_preview_v2_auth_v2');else await request('logout','POST');editorPanel.classList.add('hidden');loginPanel.classList.remove('hidden');loginStatus.textContent='';};
if(local&&sessionStorage.getItem('bufalo_blog_preview_v2_auth_v2')==='1'){loginPanel.classList.add('hidden');editorPanel.classList.remove('hidden');document.getElementById('preview-note').classList.remove('hidden');load().then(resetForm);}

