const encoder=new TextEncoder();
const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};
const json=(value,status=200,extra={})=>new Response(JSON.stringify(value),{status,headers:{...headers,...extra}});
const hex=bytes=>Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');
const hash=async value=>hex(await crypto.subtle.digest('SHA-256',encoder.encode(value)));
async function verifyPassword(password,setting){const [salt,expected]=(setting||'').split(':');if(!salt||!/^[a-f0-9]{64}$/.test(expected||''))return false;const key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);const actual=hex(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:encoder.encode(salt),iterations:100000},key,256));let diff=0;for(let i=0;i<64;i++)diff|=actual.charCodeAt(i)^expected.charCodeAt(i);return diff===0;}
function cookie(request,token,maxAge){return `blog_session=${token}; Path=/blog; HttpOnly; SameSite=Strict; Max-Age=${maxAge}${new URL(request.url).protocol==='https:'?'; Secure':''}`;}
async function authorized(request,db){const token=request.headers.get('Cookie')?.match(/(?:^|;\s*)blog_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(!token)return false;return !!await db.prepare('SELECT token FROM blog_sessions WHERE token=? AND expires>?').bind(await hash(token),Date.now()).first();}
async function bodyOf(request){if(!request.headers.get('Content-Type')?.startsWith('application/json'))throw {status:415,error:'Formato inválido.'};const length=Number(request.headers.get('Content-Length')||0);if(length>20000)throw {status:413,error:'Texto muito grande.'};const text=await request.text();if(text.length>20000)throw {status:413,error:'Texto muito grande.'};let value;try{value=JSON.parse(text)}catch{throw {status:400,error:'Pedido inválido.'}}if(!value||typeof value!=='object'||Array.isArray(value))throw {status:400,error:'Pedido inválido.'};return value;}
const validText=(value,max,min=1)=>typeof value==='string'&&value.trim().length>=min&&value.trim().length<=max;
function validate(p){if(!p||typeof p!=='object'||Array.isArray(p))return 'Post inválido.';if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug||'')||p.slug.length>90)return 'Identificador inválido.';if(!validText(p.title,120)||!validText(p.category,40)||!validText(p.excerpt,260,20)||!validText(p.imageAlt,160)||!validText(p.body,15000,80))return 'Revise os campos obrigatórios e seus tamanhos.';if(!/^\d{4}-\d{2}-\d{2}$/.test(p.date||'')||Number.isNaN(Date.parse(p.date)))return 'Data inválida.';if(!['draft','published'].includes(p.status))return 'Status inválido.';if(typeof p.image!=='string'||p.image.length>1000||!(p.image.startsWith('/assets/')||/^https:\/\//.test(p.image)))return 'Use uma imagem do site ou URL HTTPS.';if(p.sourceUrl&&(!/^https:\/\//.test(p.sourceUrl)||p.sourceUrl.length>1000))return 'URL de origem inválida.';return null;}
async function handle({request,env}){const url=new URL(request.url),path=url.pathname.replace(/\/$/,'');if(!env.LIVE_DB)return json({error:'Banco do blog não configurado.'},503);const db=env.LIVE_DB;
  if(path==='/blog/api/posts'&&request.method==='GET'){const rows=await db.prepare("SELECT slug,title,category,excerpt,image,image_alt AS imageAlt,post_date AS date,body,status,source_url AS sourceUrl FROM blog_posts WHERE status='published' ORDER BY post_date DESC, updated_at DESC").all();return json({posts:rows.results});}
  if(['POST','DELETE'].includes(request.method)&&request.headers.get('Origin')!==url.origin)return json({error:'Origem não permitida.'},403);
  if(path==='/blog/api/login'&&request.method==='POST'){if(!env.BLOG_PASSWORD_HASH)return json({error:'Senha do blog não configurada no servidor.'},503);const body=await bodyOf(request);const now=Date.now(),bucket=Math.floor(now/900000),client=await hash((request.headers.get('CF-Connecting-IP')||'local')+':'+bucket);const attempt=await db.prepare('INSERT INTO blog_attempts(client,attempts,expires) VALUES (?,1,?) ON CONFLICT(client) DO UPDATE SET attempts=attempts+1 RETURNING attempts').bind(client,(bucket+1)*900000).first();if(attempt.attempts>8)return json({error:'Muitas tentativas. Aguarde 15 minutos.'},429,{'Retry-After':'900'});if(!validText(body.password,128)||!await verifyPassword(body.password,env.BLOG_PASSWORD_HASH))return json({error:'Senha incorreta.'},401);const token=hex(crypto.getRandomValues(new Uint8Array(32)));await db.batch([db.prepare('DELETE FROM blog_sessions WHERE expires<=?').bind(now),db.prepare('DELETE FROM blog_attempts WHERE expires<=? OR client=?').bind(now,client),db.prepare('INSERT INTO blog_sessions(token,expires) VALUES (?,?)').bind(await hash(token),now+14400000)]);return json({ok:true},200,{'Set-Cookie':cookie(request,token,14400)});}
  if(!await authorized(request,db))return json({error:'Entre no painel para continuar.'},401);
  if(path==='/blog/api/logout'&&request.method==='POST'){const token=request.headers.get('Cookie')?.match(/(?:^|;\s*)blog_session=([a-f0-9]{64})/)?.[1];if(token)await db.prepare('DELETE FROM blog_sessions WHERE token=?').bind(await hash(token)).run();return json({ok:true},200,{'Set-Cookie':cookie(request,'',0)});}
  if(path==='/blog/api/admin/posts'&&request.method==='GET'){const rows=await db.prepare('SELECT slug,title,category,excerpt,image,image_alt AS imageAlt,post_date AS date,body,status,source_url AS sourceUrl FROM blog_posts ORDER BY post_date DESC, updated_at DESC').all();return json({posts:rows.results});}
  if(path==='/blog/api/admin/posts'&&request.method==='POST'){const p=await bodyOf(request),error=validate(p);if(error)return json({error},400);const old=await db.prepare('SELECT slug FROM blog_posts WHERE slug=?').bind(p.slug).first();await db.prepare('INSERT INTO blog_posts(slug,title,category,excerpt,image,image_alt,post_date,body,status,source_url,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET title=excluded.title,category=excluded.category,excerpt=excluded.excerpt,image=excluded.image,image_alt=excluded.image_alt,post_date=excluded.post_date,body=excluded.body,status=excluded.status,source_url=excluded.source_url,updated_at=excluded.updated_at').bind(p.slug,p.title.trim(),p.category.trim(),p.excerpt.trim(),p.image.trim(),p.imageAlt.trim(),p.date,p.body.trim(),p.status,p.sourceUrl||null,new Date().toISOString()).run();return json({ok:true,created:!old});}
  const match=path.match(/^\/blog\/api\/admin\/posts\/([a-z0-9-]+)$/);if(match&&request.method==='DELETE'){await db.prepare('DELETE FROM blog_posts WHERE slug=?').bind(match[1]).run();return json({ok:true});}
  return json({error:'Rota não encontrada.'},404);
}
export async function onRequest(context){try{return await handle(context)}catch(error){return json({error:error.error||'Não foi possível acessar o blog.'},error.status||503)}}
