
const hex=bytes=>Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');
async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256));}
async function sessionDigest(token){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)));}
function authCookie(req,value,age){return 'bufalo_admin='+value+'; Path=/; HttpOnly; SameSite=Strict; Max-Age='+age+(new URL(req.url).protocol==='https:'?'; Secure':'');}
async function passwordSession(req,env){const token=cookie(req,'bufalo_admin');if(!token||!/^[a-f0-9]{64}$/.test(token))return null;const s=await env.DB.prepare('SELECT id FROM admin_sessions WHERE id=? AND expires_at>?').bind(await sessionDigest(token),Date.now()).first();return s?'Administrador':null;}
async function login(req,env){if(!env.ADMIN_PASSWORD_HASH||!env.ADMIN_PASSWORD_SALT)return json({error:'Login ainda não configurado.'},503);const bucket=Math.floor(Date.now()/900000),ip=req.headers.get('CF-Connecting-IP')||'local';const key=await sessionDigest(env.ADMIN_PASSWORD_SALT+ip+bucket);const attempt=await env.DB.prepare('INSERT INTO login_attempts (id,attempts,expires_at) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET attempts=attempts+1 RETURNING attempts').bind(key,Date.now()+1800000).first();if(attempt.attempts>10)return json({error:'Muitas tentativas. Aguarde 15 minutos.'},429);const body=await readJson(req,2048);const actual=await passwordHash(String(body.password||''),env.ADMIN_PASSWORD_SALT);let diff=actual.length^env.ADMIN_PASSWORD_HASH.length;for(let i=0;i<actual.length;i++)diff|=actual.charCodeAt(i)^(env.ADMIN_PASSWORD_HASH.charCodeAt(i)||0);if(diff)return json({error:'Senha incorreta.'},401);const token=hex(crypto.getRandomValues(new Uint8Array(32)));await env.DB.prepare('INSERT INTO admin_sessions (id,expires_at) VALUES (?,?)').bind(await sessionDigest(token),Date.now()+28800000).run();await env.DB.batch([env.DB.prepare('DELETE FROM admin_sessions WHERE expires_at<?').bind(Date.now()),env.DB.prepare('DELETE FROM login_attempts WHERE expires_at<?').bind(Date.now())]);return json({ok:true},200,{'Set-Cookie':authCookie(req,token,28800)});}
async function logout(req,env){const token=cookie(req,'bufalo_admin');if(token)await env.DB.prepare('DELETE FROM admin_sessions WHERE id=?').bind(await sessionDigest(token)).run();return json({ok:true},200,{'Set-Cookie':authCookie(req,'',0)});}
const json=(data,status=200,headers={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}});
const now=()=>new Date().toISOString();
const cookie=(req,key)=>req.headers.get('Cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(key+'='))?.slice(key.length+1);
const uuid=/^[a-f0-9-]{36}$/i;
const clean=(v,max=160)=>String(v??'').replace(/[\u0000-\u001f]/g,'').slice(0,max);
const rows=async stmt=>(await stmt.all()).results;
const defaults=[{id:'campanha-cliente',title:'Mês do cliente',alt:'Mês do cliente Búfalo: vantagens para a manada',desktop:'https://cdn.awsli.com.br/1920x1920/1237/1237589/banner/banner-site-usar-esse-93-hqpv0pmcj7.jpg',mobile:'https://cdn.awsli.com.br/1920x1920/1237/1237589/banner/banner-site-usar-esse-95-vboyuhy9q4.jpg',target:'https://www.bufalogrowler.com.br/ofertas',position:0},{id:'colecao-garrafas',title:'Coleção de garrafas',alt:'Conheça a coleção de garrafas Búfalo Growler',desktop:'https://cdn.awsli.com.br/1140x850/1237/1237589/banner/3-fo5zo3zwz9.png',mobile:null,target:'https://www.bufalogrowler.com.br/garrafas',position:1}];
export function safeTarget(v){try{const u=new URL(v);if(!['https:','http:'].includes(u.protocol))throw 0;return u.href.slice(0,1000)}catch{throw new Error('Informe um link http ou https válido.')}}
function dateValue(v){if(!v)return null;const d=new Date(v);if(!Number.isFinite(+d))throw new Error('Data inválida.');return d.toISOString()}
export function attribution(input,origin){let host='';try{host=new URL(input.referrer).hostname}catch{}const own=new URL(origin).hostname;if(host===own)host='';const source=clean(input.source||host||'Direto',100);return{source,medium:clean(input.medium||(host?'referência':'nenhum'),80),campaign:clean(input.campaign||'Sem campanha',120),referrer:host};}
async function readJson(req,max=8192){const text=await bounded(req,max);try{return JSON.parse(new TextDecoder().decode(text))}catch{throw new Error('Dados inválidos.')}}
async function bounded(req,max){const reader=req.body?.getReader();if(!reader)return new Uint8Array();const chunks=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new Error('Arquivo ou solicitação excede o limite.')}chunks.push(value)}const output=new Uint8Array(size);let p=0;for(const c of chunks){output.set(c,p);p+=c.length}return output;}
export async function administrator(req,env){const u=new URL(req.url);if(env.ADMIN_PASSWORD_HASH)return passwordSession(req,env);if(env.LOCAL_DEV==='true'&&['127.0.0.1','localhost','[::1]'].includes(u.hostname))return 'Prévia local';if(!env.ACCESS_TEAM||!env.ACCESS_AUD||!env.ADMIN_EMAILS)return null;const token=req.headers.get('Cf-Access-Jwt-Assertion')||cookie(req,'CF_Authorization');if(!token)return null;try{const parts=token.split('.');if(parts.length!==3)return null;const decode=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const header=JSON.parse(new TextDecoder().decode(decode(parts[0]))),claims=JSON.parse(new TextDecoder().decode(decode(parts[1])));const issuer=env.ACCESS_TEAM.replace(/\/$/,'');if(header.alg!=='RS256'||claims.iss!==issuer||!Number.isFinite(claims.exp)||claims.exp<=Date.now()/1000||claims.nbf>Date.now()/1000||!Array.isArray(claims.aud)||!claims.aud.includes(env.ACCESS_AUD))return null;const allowed=env.ADMIN_EMAILS.split(',').map(e=>e.trim().toLowerCase());if(!allowed.includes(String(claims.email).toLowerCase()))return null;const result=await fetch(issuer+'/cdn-cgi/access/certs',{signal:AbortSignal.timeout(5000)});if(!result.ok)return null;const jwk=(await result.json()).keys.find(k=>k.kid===header.kid);if(!jwk)return null;const key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);return await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,decode(parts[2]),new TextEncoder().encode(parts[0]+'.'+parts[1]))?claims.email:null}catch{return null}}
async function audit(env,actor,action,entity){await env.DB.prepare('INSERT INTO audit VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),actor,action,entity,now()).run()}
async function resolveMedia(env,value){if(!value)return null;if(value.startsWith('https://cdn.awsli.com.br/'))return{url:value,mime:'image/jpeg'};if(!uuid.test(value))throw new Error('Selecione uma mídia da biblioteca.');const item=await env.DB.prepare('SELECT id,mime FROM media WHERE id=?').bind(value).first();if(!item)throw new Error('Mídia não encontrada.');return{url:'/media/'+item.id,mime:item.mime}}
async function publicBanners(env){const at=now();const list=await rows(env.DB.prepare('SELECT * FROM banners WHERE archived=0 AND active=1 AND (starts_at IS NULL OR starts_at<=?) AND (ends_at IS NULL OR ends_at>?) ORDER BY position,created_at').bind(at,at));return Promise.all(list.map(async b=>({...b,desktop:await resolveMedia(env,b.desktop),mobile:await resolveMedia(env,b.mobile)})))}
async function saveBanner(req,env,id){const b=await readJson(req);const title=clean(b.title,100).trim(),alt=clean(b.alt,240).trim();if(!title||!alt||!b.desktop)throw new Error('Preencha título, descrição e mídia desktop.');await resolveMedia(env,b.desktop);await resolveMedia(env,b.mobile);const target=safeTarget(b.target),start=dateValue(b.starts_at),end=dateValue(b.ends_at);if(start&&end&&start>=end)throw new Error('O fim deve ser posterior ao início.');const existing=id?await env.DB.prepare('SELECT * FROM banners WHERE id=?').bind(id).first():null;if(id&&!existing)return json({error:'Banner não encontrado.'},404);const key=id||crypto.randomUUID(),at=now();const position=existing?.position??((await env.DB.prepare('SELECT COALESCE(MAX(position),0)+1 AS next FROM banners').first()).next);await env.DB.prepare('INSERT INTO banners (id,title,alt,desktop,mobile,target,active,position,starts_at,ends_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,alt=excluded.alt,desktop=excluded.desktop,mobile=excluded.mobile,target=excluded.target,active=excluded.active,starts_at=excluded.starts_at,ends_at=excluded.ends_at,updated_at=excluded.updated_at').bind(key,title,alt,b.desktop,b.mobile||null,target,b.active?1:0,position,start,end,existing?.created_at||at,at).run();return json({id:key});}
export function validSignature(bytes,mime){const a=[...bytes.slice(0,12)];if(mime==='image/jpeg')return a[0]===255&&a[1]===216&&a[2]===255;if(mime==='image/png')return a.slice(0,8).join(',')==='137,80,78,71,13,10,26,10';const text=new TextDecoder().decode(bytes.slice(0,12));if(mime==='image/webp')return text.startsWith('RIFF')&&text.slice(8)==='WEBP';if(mime==='image/gif')return text.startsWith('GIF87a')||text.startsWith('GIF89a');if(mime==='video/mp4')return text.slice(4,8)==='ftyp';if(mime==='video/webm')return a.slice(0,4).join(',')==='26,69,223,163';return false;}
async function upload(req,env){if(!env.MEDIA)return json({error:'Uploads aguardam a ativação do armazenamento na Cloudflare.'},503);const mime=req.headers.get('Content-Type')?.split(';')[0],size=Number(req.headers.get('Content-Length'));const limit=30*1024*1024;if(size>limit)return json({error:'Máximo de 30 MB por arquivo.'},413);if(!['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm'].includes(mime))return json({error:'Use JPG, PNG, WebP, GIF, MP4 ou WebM.'},415);const bytes=await bounded(req,limit);if(bytes.length<12||!validSignature(bytes,mime))return json({error:'O conteúdo não corresponde ao formato informado.'},415);const id=crypto.randomUUID(),filename=clean(decodeURIComponent(req.headers.get('X-Filename')||'midia'),180);await env.MEDIA.put(id,bytes,{httpMetadata:{contentType:mime}});try{await env.DB.prepare('INSERT INTO media VALUES (?,?,?,?,?,?)').bind(id,id,filename,mime,bytes.length,now()).run()}catch(e){await env.MEDIA.delete(id);throw e}return json({id,filename,mime,size:bytes.length,url:'/media/'+id},201)}
async function mediaResponse(req,env,id,actor){if(!uuid.test(id))return new Response('Não encontrado',{status:404});const m=await env.DB.prepare('SELECT * FROM media WHERE id=?').bind(id).first();if(!m)return new Response('Não encontrado',{status:404});if(!actor){const at=now();const visible=await env.DB.prepare('SELECT id FROM banners WHERE archived=0 AND active=1 AND (desktop=? OR mobile=?) AND (starts_at IS NULL OR starts_at<=?) AND (ends_at IS NULL OR ends_at>?) LIMIT 1').bind(id,id,at,at).first();if(!visible)return new Response('Não encontrado',{status:404})}const range=req.headers.get('Range');const object=await env.MEDIA.get(m.object_key,range?{range:req.headers}:{});if(!object)return new Response('Não encontrado',{status:404});const headers=new Headers({'Content-Type':m.mime,'X-Content-Type-Options':'nosniff','Accept-Ranges':'bytes','Cache-Control':'private,no-store'});let status=200;if(range&&object.range){const {offset=0,length}=object.range;if(length){headers.set('Content-Range',`bytes ${offset}-${offset+length-1}/${object.size}`);headers.set('Content-Length',String(length));status=206}}else headers.set('Content-Length',String(object.size));return new Response(req.method==='HEAD'?null:object.body,{status,headers})}
async function session(req,env){if(/bot|crawler|spider|headless/i.test(req.headers.get('User-Agent')||''))return json({tracking:false});const b=await readJson(req),old=cookie(req,'bufalo_visit'),cutoff=new Date(Date.now()-1800000).toISOString();const existing=old&&uuid.test(old)?await env.DB.prepare('SELECT id FROM sessions WHERE id=? AND last_seen>?').bind(old,cutoff).first():null;const id=existing?.id||crypto.randomUUID(),at=now();if(existing)await env.DB.prepare('UPDATE sessions SET last_seen=? WHERE id=?').bind(at,id).run();else{const a=attribution(b,req.url),device=/ipad|tablet/i.test(req.headers.get('User-Agent')||'')?'Tablet':/mobile|android|iphone/i.test(req.headers.get('User-Agent')||'')?'Mobile':'Desktop';await env.DB.prepare('INSERT INTO sessions VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,at,at,a.source,a.medium,a.campaign,a.referrer,device,clean(req.cf?.country||'Não disponível',30),'/' ).run()}return json({tracking:true},200,{'Set-Cookie':`bufalo_visit=${id}; Path=/; HttpOnly; SameSite=Lax; Max-Age=1800${new URL(req.url).protocol==='https:'?'; Secure':''}`})}
async function collect(req,env){const id=cookie(req,'bufalo_visit');if(!id||!uuid.test(id))return json({error:'Sessão ausente'},401);const valid=await env.DB.prepare('SELECT id FROM sessions WHERE id=? AND last_seen>?').bind(id,new Date(Date.now()-1800000).toISOString()).first();if(!valid)return json({error:'Sessão expirada'},401);const b=await readJson(req);if(!['page_view','banner_view','banner_click','outbound_click'].includes(b.type)||!uuid.test(b.view_id)||!uuid.test(b.id))return json({error:'Evento inválido'},400);const cap=await env.DB.prepare('SELECT COUNT(*) AS n FROM events WHERE session_id=?').bind(id).first();if(cap.n>=500)return json({error:'Limite da sessão atingido'},429);if(b.type.startsWith('banner_')){const item=await env.DB.prepare('SELECT id FROM banners WHERE id=? AND archived=0').bind(clean(b.banner_id,100)).first();if(!item)return json({error:'Banner desconhecido'},400)}await env.DB.prepare('INSERT OR IGNORE INTO events VALUES (?,?,?,?,?,?,?,?,?)').bind(b.id,id,b.type,'/',b.type.startsWith('banner_')?clean(b.banner_id,100):null,clean(b.label,120),b.type==='outbound_click'?safeTarget(b.destination):'',b.view_id,now()).run();await env.DB.prepare('UPDATE sessions SET last_seen=? WHERE id=?').bind(now(),id).run();return json({ok:true})}
async function analytics(url,env){const days=Math.min(90,Math.max(1,Number(url.searchParams.get('days'))||30));const from=new Date(Date.now()-days*86400000).toISOString();const q=sql=>env.DB.prepare(sql).bind(from);const summary=await q("SELECT COUNT(DISTINCT session_id) AS sessions,SUM(type='page_view') AS views,SUM(type='banner_view') AS impressions,SUM(type='banner_click') AS bannerClicks,SUM(type='outbound_click') AS outbound FROM events WHERE created_at>=?").first();const daily=await rows(q("SELECT substr(created_at,1,10) AS day,SUM(type='page_view') AS views,SUM(type='banner_click' OR type='outbound_click') AS clicks FROM events WHERE created_at>=? GROUP BY day ORDER BY day"));const sources=await rows(q("SELECT s.source,s.medium,s.campaign,COUNT(DISTINCT e.session_id) AS sessions,SUM(e.type='page_view') AS views,SUM(e.type='banner_click' OR e.type='outbound_click') AS clicks FROM events e JOIN sessions s ON s.id=e.session_id WHERE e.created_at>=? GROUP BY s.source,s.medium,s.campaign ORDER BY sessions DESC LIMIT 100"));const devices=await rows(q("SELECT s.device,COUNT(DISTINCT e.session_id) AS sessions FROM events e JOIN sessions s ON s.id=e.session_id WHERE e.created_at>=? GROUP BY s.device"));const countries=await rows(q("SELECT s.country,COUNT(DISTINCT e.session_id) AS sessions FROM events e JOIN sessions s ON s.id=e.session_id WHERE e.created_at>=? GROUP BY s.country ORDER BY sessions DESC LIMIT 30"));const banners=await rows(q("SELECT e.banner_id,COALESCE(b.title,'Banner arquivado') AS title,SUM(e.type='banner_view') AS views,SUM(e.type='banner_click') AS clicks FROM events e LEFT JOIN banners b ON b.id=e.banner_id WHERE e.created_at>=? AND e.type IN ('banner_view','banner_click') GROUP BY e.banner_id ORDER BY clicks DESC"));const links=await rows(q("SELECT label,destination,COUNT(*) AS clicks FROM events WHERE created_at>=? AND type='outbound_click' GROUP BY label,destination ORDER BY clicks DESC LIMIT 30"));const latest=await rows(q("SELECT e.created_at,e.type,e.label,s.source,s.medium,s.campaign,s.device FROM events e JOIN sessions s ON s.id=e.session_id WHERE e.created_at>=? ORDER BY e.created_at DESC LIMIT 100"));return json({days,from,timezone:'UTC',summary,daily,sources,devices,countries,banners,links,latest,generatedAt:now(),retentionDays:90})}
async function route(req,env){const url=new URL(req.url),p=url.pathname;const write=!['GET','HEAD'].includes(req.method);if(write){const origin=req.headers.get('Origin');if(origin!==url.origin)return json({error:'Origem não permitida.'},403)}if(p==='/api/auth/login'&&req.method==='POST')return login(req,env);if(p==='/api/auth/logout'&&req.method==='POST')return logout(req,env);if(p==='/api/banners'&&req.method==='GET')return json({banners:await publicBanners(env),interval:2000});if(p==='/api/session'&&req.method==='POST')return session(req,env);if(p==='/api/events'&&req.method==='POST')return collect(req,env);
const needsAdmin=p==='/admin'||p==='/admin/'||p==='/admin.html'||p.startsWith('/api/admin/')||p.startsWith('/media/');const actor=needsAdmin?await administrator(req,env):null;if(p.startsWith('/media/'))return mediaResponse(req,env,p.split('/')[2],actor);
if(needsAdmin&&!actor){if(!p.startsWith('/api/')&&env.ADMIN_PASSWORD_HASH){const page=await env.ASSETS.fetch(new Request(new URL('/login',url),req));return new Response(page.body,{status:401,headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store'}});}if(p.startsWith('/api/'))return json({error:'Entre com uma conta administradora autorizada.'},401);return new Response('<html lang="pt-BR"><meta charset="utf-8"><title>Acesso protegido</title><body style="font:18px Arial;padding:10%;"><h1>Painel protegido</h1><p>O acesso administrativo precisa ser configurado no Cloudflare Access.</p><a href="/">Voltar ao site</a></body></html>',{status:401,headers:{'Content-Type':'text/html;charset=utf-8'}})}
if(p==='/api/admin/context')return json({actor,local:actor==='Prévia local',interval:2000});
if(p==='/api/admin/banners'&&req.method==='GET')return json({banners:await rows(env.DB.prepare('SELECT * FROM banners ORDER BY position,created_at'))});
if(p==='/api/admin/banners'&&req.method==='POST'){const result=await saveBanner(req,env,null);await audit(env,actor,'criar banner','novo');return result}
if(p==='/api/admin/seed'&&req.method==='POST'){const count=await env.DB.prepare('SELECT COUNT(*) AS n FROM banners').first();if(count.n)return json({error:'A biblioteca já possui banners.'},409);const at=now();await env.DB.batch(defaults.map(b=>env.DB.prepare('INSERT INTO banners (id,title,alt,desktop,mobile,target,active,position,created_at,updated_at) VALUES (?,?,?,?,?,?,1,?,?,?)').bind(b.id,b.title,b.alt,b.desktop,b.mobile,b.target,b.position,at,at)));await audit(env,actor,'adicionar banners iniciais','');return json({ok:true})}
if(p==='/api/admin/reorder'&&req.method==='POST'){const b=await readJson(req);if(!Array.isArray(b.ids)||b.ids.length>100||new Set(b.ids).size!==b.ids.length)return json({error:'Ordem inválida'},400);const ids=await rows(env.DB.prepare('SELECT id FROM banners'));if(b.ids.length!==ids.length||!b.ids.every(id=>ids.some(x=>x.id===id)))return json({error:'Atualize a lista antes de ordenar.'},409);await env.DB.batch(b.ids.map((id,i)=>env.DB.prepare('UPDATE banners SET position=? WHERE id=?').bind(i,id)));await audit(env,actor,'reordenar banners','');return json({ok:true})}
const banner=p.match(/^\/api\/admin\/banners\/([a-zA-Z0-9-]+)$/);if(banner&&req.method==='PUT'){const result=await saveBanner(req,env,banner[1]);await audit(env,actor,'editar banner',banner[1]);return result}
const archive=p.match(/^\/api\/admin\/banners\/([a-zA-Z0-9-]+)\/archive$/);if(archive&&req.method==='POST'){const b=await readJson(req);await env.DB.prepare('UPDATE banners SET archived=?,updated_at=? WHERE id=?').bind(b.archived?1:0,now(),archive[1]).run();await audit(env,actor,b.archived?'arquivar banner':'restaurar banner',archive[1]);return json({ok:true})}
if(p==='/api/admin/media'&&req.method==='GET')return json({media:(await rows(env.DB.prepare('SELECT * FROM media ORDER BY created_at DESC LIMIT 200'))).map(m=>({...m,url:'/media/'+m.id}))});if(p==='/api/admin/media'&&req.method==='POST'){const r=await upload(req,env);if(r.ok)await audit(env,actor,'upload de mídia','');return r}
if(p==='/api/admin/analytics'&&req.method==='GET')return analytics(url,env);if(p==='/api/admin/audit')return json({audit:await rows(env.DB.prepare('SELECT * FROM audit ORDER BY created_at DESC LIMIT 50'))});
if(p.startsWith('/api/'))return json({error:'Rota não encontrada'},404);return env.ASSETS.fetch(new Request(url,req));}
export default{async fetch(req,env){try{const response=await route(req,env);const result=new Response(response.body,response);result.headers.set('X-Content-Type-Options','nosniff');result.headers.set('Referrer-Policy','strict-origin-when-cross-origin');result.headers.set('Content-Security-Policy',"default-src 'self'; img-src 'self' https://cdn.awsli.com.br data: blob:; media-src 'self' blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; frame-ancestors 'self'; base-uri 'self'; form-action 'self'");if(new URL(req.url).pathname.startsWith('/admin'))result.headers.set('Cache-Control','no-store');return result}catch(error){console.error(JSON.stringify({message:error.message,path:new URL(req.url).pathname}));const expected=/Informe|Preencha|Data inválida|posterior|Selecione|Mídia não|Dados inválidos|excede/.test(error.message);return json({error:expected?error.message:'Não foi possível concluir. Tente novamente.'},expected?400:500)}},async scheduled(_event,env){const cutoff=new Date(Date.now()-90*86400000).toISOString();await env.DB.batch([env.DB.prepare('DELETE FROM events WHERE created_at<?').bind(cutoff),env.DB.prepare('DELETE FROM sessions WHERE last_seen<? AND id NOT IN (SELECT session_id FROM events)').bind(cutoff),env.DB.prepare('DELETE FROM audit WHERE created_at<?').bind(cutoff)])}};




